channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5
  - qt=5.12.9
  - pyqt=5.12.3
  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - pywebview[qt]==3.6.3
      - rpaframework==15.1.4 # https://rpaframework.org/releasenotes.html
